UndergroundStation/UndergroundStation.Web/Areas/Forum/Models/Sections/SectionCreateFormModel.cs
namespace UndergroundStation.Web.Areas.Forum.Models.Sections
{
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using Data.Models;

    using static Data.DataConstants;

    public class SectionCreateFormModel
    {
        [Required]
        [MinLength(ForumSectionTitleMinLenght)]
        [MaxLength(ForumSectionTitleMaxLenght)]
        public string Title { get; set; }

        [Required]
        [MinLength(ForumSectionDescriptionMinLenght)]
        [MaxLength(ForumSectionDescriptionMaxLenght)]
        public string Description { get; set; }
    }
}

UndergroundStation/UndergroundStation.Web/Areas/Forum/Models/Sections/SectionsDetailsViewModel.cs
namespace UndergroundStation.Web.Areas.Forum.Models.Sections
{
    using Services.Forum.Models;
    using System.Collections.Generic;

    public class SectionsDetailsViewModel
    {
        public SectionDetailsServiceModel SectionDetails { get; set; }

        public IEnumerable<ThemeListingServiceModel> Themes { get; set; }
    }
}

UndergroundStation/UndergroundStation.Web/Areas/Forum/Controllers/SectionsController.cs
namespace UndergroundStation.Web.Areas.Forum.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using Services.Forum;
    using Models.Sections;
    using Infrastructure.Extentions;
    using Microsoft.AspNetCore.Identity;
    using Models.Themes;
    using Data.Models;

    using static WebConstants;

    [Area(ForumArea)]
    public class SectionsController : Controller
    {
        private readonly ISectionsService sections;
        private readonly IThemesService themes;
        private readonly UserManager<User> userManager;

        public SectionsController
            (ISectionsService sections,
            IThemesService themes,
            UserManager<User> userManager)
        {
            this.sections = sections;
            this.themes = themes;
            this.userManager = userManager;
        }

        [Authorize(Roles = ForumModeratorRole)]
        public IActionResult Create()
           => View();

        [Authorize(Roles = ForumModeratorRole)]
        [HttpPost]
        public async Task<IActionResult> Create(SectionCreateFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            if (model.Description == null || model.Title == null)
            {
                return BadRequest();
            }

            var success = await sections.Create(model.Title, model.Description);

            if (!success)
            {
                return BadRequest();
            }

            TempData.AddSuccessMessage($"Article {model.Title} successfully published.");

            return Redirect("/Forum/Home/Index");
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {

            var secDetails = await this.sections.ByIdAsync(id);

            var themes = await this.themes.BySectionIdAsync(id);

            var section = 
                new SectionsDetailsViewModel
            {
                SectionDetails = secDetails,
                Themes = themes
            };

            return View(section);
        }

        [Authorize]
        public async Task< IActionResult> AddTheme(int id)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);

            if (user.Id == null)
            {
                return NotFound();
            }

            var model = new ThemeCreateFormModel
            {
                PublishedDate = DateTime.UtcNow,
                CreatorId = user.Id,
                ForumSectionId = id
            };
           

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddTheme(ThemeCreateFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var success = await themes.CreateThemeAsync
                (model.Title,
                 model.Description,
                 model.CreatorId,
                 model.ForumSectionId,
                 model.PublishedDate);

            if (!success)
            {
                return BadRequest();
            }

            TempData.AddSuccessMessage($"Theme {model.Title} successfully published.");

            return Redirect($"/forum/sections/details/{model.ForumSectionId}");
        }

    }
}

UndergroundStation/UndergroundStation.Web/Areas/Forum/Views/Sections/AddTheme.cshtml
@model ThemeCreateFormModel

@{
    ViewData["Title"] = $"Add Theme";
}
<br />
<br />
<br />
<h2>@ViewData["Title"]</h2>

<div class="row" >
    <div class="col-sm-4" >
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="10" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="hidden"  asp-for="CreatorId" rows="10" class="form-control">
                <span asp-validation-for="CreatorId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="hidden" asp-for="ForumSectionId" rows="10" class="form-control">
                <span asp-validation-for="ForumSectionId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="hidden" asp-for="PublishedDate" rows="10" class="form-control">
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
           
            <button type="submit" class="btn btn-success">Add Theme</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

UndergroundStation/UndergroundStation.Web/Areas/Forum/Views/Sections/Create.cshtml
@model SectionCreateFormModel
@{
    ViewData["Title"] = "Create Section";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-5">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="10" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>   
            <button type="submit" class="btn btn-default">Add Section</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

UndergroundStation/UndergroundStation.Web/Areas/Forum/Views/Sections/Details.cshtml
@model SectionsDetailsViewModel
@using System.Linq
@{
    ViewData["Title"] = Model.SectionDetails.Tittle;
}
<br />
<br />

<div class="row" align="center">
    <h1><a asp-area="Forum" asp-controller="Home" asp-action="Index">Forum</a> @($"/{Model.SectionDetails.Tittle}")</h1>
</div>


<div class="jumbotron">
    <h3 class="col-md-offset-1">Themes</h3>
    <ul>
        @foreach (var theme in Model.Themes)
        {
            var dict =
               new Dictionary<string, string>
                   {
                  {"themeId", theme.Id.ToString()},
                  {"page", "1"},
                   };

            <li>
                <h3>
                    <a asp-area="Forum" asp-controller="Themes" asp-action="Details" asp-all-route-data="@dict">@theme.Title</a>
                </h3>
                <h5>By <a asp-area="" asp-controller="Account" asp-action="Profile" asp-route-username="@theme.CreatorName">@theme.CreatorName</a></h5>
                <h5>Open at: @($"{theme.PublishedDate.ToShortTimeString()} on {theme.PublishedDate.ToShortDateString()}")</h5>
                <h5>Answers: @(theme.ArticlesCount)</h5>
                @if (User.IsInRole(WebConstants.ForumModeratorRole))
                {
                        <form asp-area="Forum" asp-controller="Themes" asp-action="DeleteTheme" asp-route-themeId="@theme.Id" asp-route-sectionId="@Model.SectionDetails.Id" model="post">
                            <input type="submit" class="btn btn-danger btn-sm" value="Delete" )" />
                        </form>
                }
                

            </li>
        }

    </ul>
    <p align="right">
        <a class="btn btn-primary btn-sm" asp-area="Forum" asp-controller="Sections" asp-action="AddTheme" asp-route-id="@Model.SectionDetails.Id">Add Theme</a>
    </p>
</div>